# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
images:
- name: egress-filter-firewaller
  sourceRepository: github.com/gardener/egress-filter-refresher
  repository: eu.gcr.io/gardener-project/gardener/egress-filter-firewaller
  tag: "0.12.1"
- name: egress-filter-blackholer
  sourceRepository: github.com/gardener/egress-filter-refresher
  repository: eu.gcr.io/gardener-project/gardener/egress-filter-blackholer
  tag: "0.12.1"
